#!/usr/bin/env ruby
# frozen_string_literal: true

# BDF to C header converter for dvi_font_t.
# Generates a C header file from one or more BDF bitmap fonts.
#
# Usage: ruby bdf2c.rb <input.bdf> [options]
#   -o FILE     Output file (default: stdout)
#   -n NAME     Font variable name (default: derived from filename)
#   -r RANGE    Character range as "first-last" (default: 0x20-0x7f)
#   --jis       JIS X 0208 mode: use linear ku-ten indexing
#   --bold FILE Bold BDF file to interleave with regular
#              (generates interleaved regular+bold bitmap)

require "optparse"

class BDFGlyph
  attr_accessor :encoding, :dwidth, :width, :height, :x_offset, :y_offset, :bitmap_rows

  def initialize
    @dwidth = 0
    @bitmap_rows = []
  end
end

class BDFParser
  attr_reader :glyphs, :fbb_width, :fbb_height, :fbb_x_offset, :fbb_y_offset

  def initialize(io)
    @glyphs = {}
    @fbb_width = 0
    @fbb_height = 0
    @fbb_x_offset = 0
    @fbb_y_offset = 0
    parse(io)
  end

  private

  def parse(io)
    current_glyph = nil
    in_bitmap = false

    io.each_line do |line|
      line = line.strip
      tokens = line.split

      case tokens[0]
      when "FONTBOUNDINGBOX"
        @fbb_width = tokens[1].to_i
        @fbb_height = tokens[2].to_i
        @fbb_x_offset = tokens[3].to_i
        @fbb_y_offset = tokens[4].to_i
      when "STARTCHAR"
        current_glyph = BDFGlyph.new
      when "ENCODING"
        current_glyph.encoding = tokens[1].to_i if current_glyph
      when "DWIDTH"
        current_glyph.dwidth = tokens[1].to_i if current_glyph
      when "BBX"
        if current_glyph
          current_glyph.width = tokens[1].to_i
          current_glyph.height = tokens[2].to_i
          current_glyph.x_offset = tokens[3].to_i
          current_glyph.y_offset = tokens[4].to_i
        end
      when "BITMAP"
        in_bitmap = true if current_glyph
      when "ENDCHAR"
        if current_glyph
          @glyphs[current_glyph.encoding] = current_glyph
          current_glyph = nil
          in_bitmap = false
        end
      else
        if in_bitmap && current_glyph
          current_glyph.bitmap_rows << tokens[0].to_i(16)
        end
      end
    end
  end
end

def render_glyph(glyph, fbb_width, fbb_height, fbb_x_offset, fbb_y_offset)
  bytes_per_row = (fbb_width + 7) / 8
  src_bytes_per_row = (glyph.width + 7) / 8
  rows = Array.new(fbb_height, 0)

  # Place glyph bitmap into the bounding box, aligning from the top.
  # BDF y_offset is relative to the baseline; fbb_y_offset is the font's
  # global descent (typically negative).
  y_start = fbb_height - (glyph.y_offset - fbb_y_offset) - glyph.height

  # BDF bitmaps are MSB-aligned within their byte storage.
  # Shift to position the glyph's x_offset within the font bounding box.
  shift = (bytes_per_row - src_bytes_per_row) * 8 - (glyph.x_offset - fbb_x_offset)

  glyph.bitmap_rows.each_with_index do |row_bits, i|
    y = y_start + i
    next if y < 0 || y >= fbb_height

    if shift > 0
      row_bits <<= shift
    elsif shift < 0
      row_bits >>= -shift
    end

    # Mask to bounding box width
    mask = ((1 << fbb_width) - 1) << (bytes_per_row * 8 - fbb_width)
    rows[y] = row_bits & mask
  end

  # Pack into bytes
  rows.flat_map do |row|
    bytes_per_row.times.map do |b|
      (row >> (8 * (bytes_per_row - 1 - b))) & 0xFF
    end
  end
end

def render_glyph_bytes(bdf, code_or_glyph, bytes_per_glyph)
  glyph = code_or_glyph.is_a?(BDFGlyph) ? code_or_glyph : bdf.glyphs[code_or_glyph]
  if glyph
    render_glyph(glyph, bdf.fbb_width, bdf.fbb_height, bdf.fbb_x_offset, bdf.fbb_y_offset)
  else
    Array.new(bytes_per_glyph, 0)
  end
end

def glyph_advance_width(bdf, code)
  glyph = bdf.glyphs[code]
  return bdf.fbb_width unless glyph
  glyph.dwidth > 0 ? glyph.dwidth : glyph.x_offset + glyph.width
end

def proportional?(bdf, first_char, last_char)
  widths = (first_char..last_char).map { |c| glyph_advance_width(bdf, c) }
  widths.uniq.length > 1
end

def generate_header(font_name, bdf, first_char, last_char)
  guard = "DVI_FONT_#{font_name.upcase}_H"
  bytes_per_row = (bdf.fbb_width + 7) / 8
  bytes_per_glyph = bytes_per_row * bdf.fbb_height
  num_chars = last_char - first_char + 1
  is_proportional = proportional?(bdf, first_char, last_char)

  lines = []
  lines << "// Generated by bdf2c.rb"
  lines << "#ifndef #{guard}"
  lines << "#define #{guard}"
  lines << ""
  lines << "#include \"dvi_font.h\""
  lines << ""
  lines << "static const uint8_t font_#{font_name}_bitmap[] = {"

  (first_char..last_char).each do |code|
    bytes = render_glyph_bytes(bdf, code, bytes_per_glyph)
    hex = bytes.map { |b| "0x%02x" % b }.join(", ")
    if code >= 0x20 && code <= 0x7E
      lines << "    #{hex},  // 0x%02x '%s'" % [code, code.chr]
    else
      lines << "    #{hex},  // 0x%02x" % code
    end
  end

  lines << "};"

  if is_proportional
    lines << ""
    lines << "static const uint8_t font_#{font_name}_widths[] = {"
    (first_char..last_char).each_slice(16) do |codes|
      vals = codes.map { |c| "%2d" % glyph_advance_width(bdf, c) }.join(", ")
      lines << "    #{vals},"
    end
    lines << "};"
  end

  lines << ""
  lines << "static const dvi_font_t font_#{font_name} = {"
  lines << "    .glyph_width  = #{bdf.fbb_width},"
  lines << "    .glyph_height = #{bdf.fbb_height},"
  lines << "    .first_char   = 0x%04x," % first_char
  lines << "    .num_chars    = #{num_chars},"
  lines << "    .bitmap       = font_#{font_name}_bitmap,"
  if is_proportional
    lines << "    .widths       = font_#{font_name}_widths,"
  end
  lines << "};"
  lines << ""
  lines << "#endif"
  lines << ""
  lines.join("\n")
end

# Generate header using JIS X 0208 linear indexing.
# JIS encoding: (ku+0x20)*256 + (ten+0x20), ku/ten are 1-indexed (1-94).
# Linear index: (ku-1)*94 + (ten-1), range 0..8835 (94*94-1).
def build_jis_glyph_map(bdf)
  jis_glyphs = {}
  bdf.glyphs.each do |enc, glyph|
    ku = (enc >> 8) - 0x20
    ten = (enc & 0xFF) - 0x20
    next unless ku >= 1 && ku <= 94 && ten >= 1 && ten <= 94
    linear = (ku - 1) * 94 + (ten - 1)
    jis_glyphs[linear] = glyph
  end
  jis_glyphs
end

def generate_jis_header(font_name, bdf)
  guard = "DVI_FONT_#{font_name.upcase}_H"
  bytes_per_row = (bdf.fbb_width + 7) / 8
  bytes_per_glyph = bytes_per_row * bdf.fbb_height
  num_chars = 94 * 94

  jis_glyphs = build_jis_glyph_map(bdf)
  $stderr.puts "JIS mode: #{jis_glyphs.size}/#{num_chars} slots populated"

  lines = []
  lines << "// Generated by bdf2c.rb (JIS X 0208 linear index mode)"
  lines << "// Linear index = (ku-1)*94 + (ten-1), ku/ten 1-indexed"
  lines << "//"
  lines << "// To convert a JIS code to linear index:"
  lines << "//   int ku  = (jis_code >> 8) - 0x20;"
  lines << "//   int ten = (jis_code & 0xFF) - 0x20;"
  lines << "//   int idx = (ku - 1) * 94 + (ten - 1);"
  lines << "#ifndef #{guard}"
  lines << "#define #{guard}"
  lines << ""
  lines << "#include \"dvi_font.h\""
  lines << ""
  lines << "static const uint8_t font_#{font_name}_bitmap[] = {"

  num_chars.times do |idx|
    bytes = render_glyph_bytes(bdf, jis_glyphs[idx], bytes_per_glyph)
    hex = bytes.map { |b| "0x%02x" % b }.join(", ")
    ku = idx / 94 + 1
    ten = idx % 94 + 1
    lines << "    #{hex},  // idx=%d ku=%d ten=%d" % [idx, ku, ten]
  end

  lines << "};"
  lines << ""
  lines << "static const dvi_font_t font_#{font_name} = {"
  lines << "    .glyph_width  = #{bdf.fbb_width},"
  lines << "    .glyph_height = #{bdf.fbb_height},"
  lines << "    .first_char   = 0,"
  lines << "    .num_chars    = #{num_chars},"
  lines << "    .bitmap       = font_#{font_name}_bitmap"
  lines << "};"
  lines << ""
  lines << "#endif"
  lines << ""
  lines.join("\n")
end

# Generate interleaved regular+bold header.
# Layout: [ch0_regular, ch0_bold, ch1_regular, ch1_bold, ...]
# Stride per glyph pair = bytes_per_glyph * 2.
# Bold offset = +bytes_per_glyph bytes from regular.
def generate_interleaved_header(font_name, reg_bdf, bold_bdf, first_char, last_char)
  # Validate matching dimensions
  unless reg_bdf.fbb_width == bold_bdf.fbb_width &&
         reg_bdf.fbb_height == bold_bdf.fbb_height
    raise "Font dimension mismatch: regular #{reg_bdf.fbb_width}x#{reg_bdf.fbb_height} " \
          "vs bold #{bold_bdf.fbb_width}x#{bold_bdf.fbb_height}"
  end

  guard = "DVI_FONT_#{font_name.upcase}_H"
  bytes_per_row = (reg_bdf.fbb_width + 7) / 8
  bytes_per_glyph = bytes_per_row * reg_bdf.fbb_height
  num_chars = last_char - first_char + 1

  lines = []
  lines << "// Generated by bdf2c.rb (interleaved regular + bold)"
  lines << "// Layout: [ch0_regular(#{bytes_per_glyph}B), ch0_bold(#{bytes_per_glyph}B), ...]"
  lines << "// Stride per glyph pair: #{bytes_per_glyph * 2} bytes"
  lines << "// Bold offset: +#{bytes_per_glyph} bytes from regular"
  lines << "#ifndef #{guard}"
  lines << "#define #{guard}"
  lines << ""
  lines << "#include \"dvi_font.h\""
  lines << ""
  lines << "static const uint8_t font_#{font_name}_bitmap[] = {"

  (first_char..last_char).each do |code|
    reg_bytes = render_glyph_bytes(reg_bdf, code, bytes_per_glyph)
    bold_bytes = render_glyph_bytes(bold_bdf, code, bytes_per_glyph)

    reg_hex = reg_bytes.map { |b| "0x%02x" % b }.join(", ")
    bold_hex = bold_bytes.map { |b| "0x%02x" % b }.join(", ")

    if code >= 0x20 && code <= 0x7E
      lines << "    #{reg_hex},  // 0x%02x '%s' regular" % [code, code.chr]
      lines << "    #{bold_hex},  // 0x%02x '%s' bold" % [code, code.chr]
    else
      lines << "    #{reg_hex},  // 0x%02x regular" % code
      lines << "    #{bold_hex},  // 0x%02x bold" % code
    end
  end

  lines << "};"
  lines << ""
  lines << "static const dvi_font_t font_#{font_name} = {"
  lines << "    .glyph_width  = #{reg_bdf.fbb_width},"
  lines << "    .glyph_height = #{reg_bdf.fbb_height},"
  lines << "    .first_char   = 0x%04x," % first_char
  lines << "    .num_chars    = #{num_chars},"
  lines << "    .bitmap       = font_#{font_name}_bitmap"
  lines << "};"
  lines << ""
  lines << "#endif"
  lines << ""
  lines.join("\n")
end

# Generate interleaved regular+bold header with JIS X 0208 indexing.
def generate_jis_interleaved_header(font_name, reg_bdf, bold_bdf)
  unless reg_bdf.fbb_width == bold_bdf.fbb_width &&
         reg_bdf.fbb_height == bold_bdf.fbb_height
    raise "Font dimension mismatch: regular #{reg_bdf.fbb_width}x#{reg_bdf.fbb_height} " \
          "vs bold #{bold_bdf.fbb_width}x#{bold_bdf.fbb_height}"
  end

  guard = "DVI_FONT_#{font_name.upcase}_H"
  bytes_per_row = (reg_bdf.fbb_width + 7) / 8
  bytes_per_glyph = bytes_per_row * reg_bdf.fbb_height
  num_chars = 94 * 94

  reg_jis = build_jis_glyph_map(reg_bdf)
  bold_jis = build_jis_glyph_map(bold_bdf)
  $stderr.puts "JIS interleaved mode: #{reg_jis.size} regular, #{bold_jis.size} bold / #{num_chars} slots"

  lines = []
  lines << "// Generated by bdf2c.rb (JIS X 0208, interleaved regular + bold)"
  lines << "// Linear index = (ku-1)*94 + (ten-1), ku/ten 1-indexed"
  lines << "// Layout: [ch0_regular(#{bytes_per_glyph}B), ch0_bold(#{bytes_per_glyph}B), ...]"
  lines << "// Stride per glyph pair: #{bytes_per_glyph * 2} bytes"
  lines << "// Bold offset: +#{bytes_per_glyph} bytes from regular"
  lines << "#ifndef #{guard}"
  lines << "#define #{guard}"
  lines << ""
  lines << "#include \"dvi_font.h\""
  lines << ""
  lines << "static const uint8_t font_#{font_name}_bitmap[] = {"

  num_chars.times do |idx|
    reg_bytes = render_glyph_bytes(reg_bdf, reg_jis[idx], bytes_per_glyph)
    bold_bytes = render_glyph_bytes(bold_bdf, bold_jis[idx], bytes_per_glyph)

    reg_hex = reg_bytes.map { |b| "0x%02x" % b }.join(", ")
    bold_hex = bold_bytes.map { |b| "0x%02x" % b }.join(", ")

    ku = idx / 94 + 1
    ten = idx % 94 + 1
    lines << "    #{reg_hex},  // idx=%d ku=%d ten=%d regular" % [idx, ku, ten]
    lines << "    #{bold_hex},  // idx=%d ku=%d ten=%d bold" % [idx, ku, ten]
  end

  lines << "};"
  lines << ""
  lines << "static const dvi_font_t font_#{font_name} = {"
  lines << "    .glyph_width  = #{reg_bdf.fbb_width},"
  lines << "    .glyph_height = #{reg_bdf.fbb_height},"
  lines << "    .first_char   = 0,"
  lines << "    .num_chars    = #{num_chars},"
  lines << "    .bitmap       = font_#{font_name}_bitmap,"
  lines << "};"
  lines << ""
  # Wide font view: same bitmap, stride 2x to skip bold glyphs.
  wide_name = font_name.sub(/_combined$/, "_wide")
  lines << "// Graphics mode: regular glyphs only (stride skips bold)."
  lines << "static const dvi_font_t font_#{wide_name} = {"
  lines << "    .glyph_width  = #{reg_bdf.fbb_width},"
  lines << "    .glyph_height = #{reg_bdf.fbb_height},"
  lines << "    .first_char   = 0,"
  lines << "    .num_chars    = #{num_chars},"
  lines << "    .bitmap       = font_#{font_name}_bitmap,"
  lines << "    .glyph_stride = #{bytes_per_glyph * 2},"
  lines << "};"
  lines << ""
  lines << "#endif"
  lines << ""
  lines.join("\n")
end

# main

options = {
  name: nil,
  output: nil,
  range: "0x20-0x7f",
  jis: false,
  bold: nil
}

OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} <input.bdf> [options]"
  opts.on("-o FILE", "Output file") { |f| options[:output] = f }
  opts.on("-n NAME", "Font variable name") { |n| options[:name] = n }
  opts.on("-r RANGE", "Character range (e.g., 0x20-0x7f)") { |r| options[:range] = r }
  opts.on("--jis", "JIS X 0208 mode: use linear ku-ten indexing") { options[:jis] = true }
  opts.on("--bold FILE", "Bold BDF file to interleave with regular") { |f| options[:bold] = f }
end.parse!

input_path = ARGV[0]
unless input_path
  $stderr.puts "Error: no input BDF file specified"
  exit 1
end

font_name = options[:name] || File.basename(input_path, ".bdf").gsub(/[^a-zA-Z0-9_]/, "_")

bdf = File.open(input_path) { |f| BDFParser.new(f) }

# Verify monospace
widths = bdf.glyphs.values.map(&:width).uniq
if widths.length > 1
  $stderr.puts "Warning: font has multiple glyph widths (#{widths.join(', ')}), using bounding box width #{bdf.fbb_width}"
end

bold_bdf = nil
if options[:bold]
  bold_bdf = File.open(options[:bold]) { |f| BDFParser.new(f) }
  bold_widths = bold_bdf.glyphs.values.map(&:width).uniq
  if bold_widths.length > 1
    $stderr.puts "Warning: bold font has multiple glyph widths (#{bold_widths.join(', ')}), using bounding box width #{bold_bdf.fbb_width}"
  end
end

def write_output(header, options, description)
  if options[:output]
    File.write(options[:output], header)
    $stderr.puts "Wrote #{options[:output]} (#{description})"
  else
    puts header
  end
end

if bold_bdf
  if options[:jis]
    header = generate_jis_interleaved_header(font_name, bdf, bold_bdf)
    bytes_per_glyph = ((bdf.fbb_width + 7) / 8) * bdf.fbb_height
    total = 94 * 94 * bytes_per_glyph * 2
    write_output(header, options,
      "#{font_name}, #{bdf.fbb_width}x#{bdf.fbb_height}, JIS X 0208 interleaved, " \
      "stride=#{bytes_per_glyph * 2}, total=#{total} bytes (#{total / 1024.0}KB)")
  else
    range_parts = options[:range].split("-")
    first_char = Integer(range_parts[0])
    last_char = Integer(range_parts[1])
    header = generate_interleaved_header(font_name, bdf, bold_bdf, first_char, last_char)
    bytes_per_glyph = ((bdf.fbb_width + 7) / 8) * bdf.fbb_height
    write_output(header, options,
      "#{font_name}, #{bdf.fbb_width}x#{bdf.fbb_height}, interleaved, " \
      "chars 0x%02x-0x%02x, stride=#{bytes_per_glyph * 2}" % [first_char, last_char])
  end
elsif options[:jis]
  header = generate_jis_header(font_name, bdf)
  write_output(header, options,
    "#{font_name}, #{bdf.fbb_width}x#{bdf.fbb_height}, JIS X 0208, #{bdf.glyphs.size} glyphs")
else
  range_parts = options[:range].split("-")
  first_char = Integer(range_parts[0])
  last_char = Integer(range_parts[1])
  header = generate_header(font_name, bdf, first_char, last_char)
  write_output(header, options,
    "#{font_name}, #{bdf.fbb_width}x#{bdf.fbb_height}, chars 0x%02x-0x%02x" % [first_char, last_char])
end
