#!/usr/bin/env ruby
# frozen_string_literal: true

# Convert font8x8 C header (LSB-first) to dvi_font_t format (MSB-first).
#
# Parses the original font8x8_basic.h array and outputs a C header with
# bit-reversed data matching the dvi_font_t convention (bit 7 = leftmost pixel).
#
# Usage: ruby font8x8_to_c.rb <input.h> [-o FILE] [-n NAME]

require "optparse"

options = { name: "font8x8_basic", output: nil }
OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} <input.h> [options]"
  opts.on("-o FILE", "Output file (default: stdout)") { |f| options[:output] = f }
  opts.on("-n NAME", "Font variable name") { |n| options[:name] = n }
end.parse!

input_path = ARGV[0] or abort "Error: no input file specified"

# Parse hex values from the C array
bytes = []
File.readlines(input_path).each do |line|
  line.scan(/0x([0-9a-fA-F]{2})/) { |m| bytes << m[0].to_i(16) }
end

abort "Error: expected 1024 bytes (128 glyphs * 8 rows), got #{bytes.size}" unless bytes.size == 1024

# Reverse bits in each byte (LSB-first -> MSB-first)
def reverse_bits(b)
  r = 0
  8.times { |i| r |= ((b >> i) & 1) << (7 - i) }
  r
end

reversed = bytes.map { |b| reverse_bits(b) }

name = options[:name]
guard = "DVI_FONT_#{name.upcase}_H"

lines = []
lines << "// Generated by font8x8_to_c.rb"
lines << "// Bit order: MSB = leftmost pixel (bit 7 = col 0), matching dvi_font_t convention."
lines << "// Source: font8x8 by Daniel Hepper (Public Domain)"
lines << ""
lines << "#ifndef #{guard}"
lines << "#define #{guard}"
lines << ""
lines << "#include <stdint.h>"
lines << "#include \"dvi_font.h\""
lines << ""
lines << "static const uint8_t #{name}_bitmap[128 * 8] = {"

128.times do |ch|
  hex = 8.times.map { |j| "0x%02X" % reversed[ch * 8 + j] }.join(", ")
  if ch >= 0x20 && ch <= 0x7E
    lines << "    #{hex},   // U+%04X (%s)" % [ch, ch.chr]
  else
    lines << "    #{hex},   // U+%04X" % ch
  end
end

lines << "};"
lines << ""
lines << "static const dvi_font_t #{name} = {"
lines << "    .glyph_width  = 8,"
lines << "    .glyph_height = 8,"
lines << "    .first_char   = 0,"
lines << "    .num_chars    = 128,"
lines << "    .bitmap       = #{name}_bitmap,"
lines << "};"
lines << ""
lines << "#endif"
lines << ""

result = lines.join("\n")

if options[:output]
  File.write(options[:output], result)
  $stderr.puts "Wrote #{options[:output]} (#{name}, 8x8, 128 glyphs, MSB-first)"
else
  puts result
end
