#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate a Unicode-to-JIS X 0208 direct lookup table as C source + header.
# Uses Ruby's built-in EUC-JP encoding to obtain the mapping.
#
# Generates a 64K-entry direct table (indexed by Unicode BMP codepoint)
# for O(1) lookup with a single flash read.
#
# Usage: ruby gen_uni2jis.rb -o FILE

require "optparse"

output = nil
OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} -o FILE"
  opts.on("-o FILE", "Output C source file (header is derived)") { |f| output = f }
end.parse!

abort "Error: -o FILE is required" unless output

# Build Unicode codepoint -> JIS code mapping via EUC-JP encoding.
direct = Array.new(65536, 0)
count = 0

(1..94).each do |ku|
  (1..94).each do |ten|
    euc_bytes = [ku + 0xA0, ten + 0xA0].pack("CC").force_encoding("EUC-JP")
    begin
      utf8 = euc_bytes.encode("UTF-8")
      codepoint = utf8.ord
      next if codepoint > 0xFFFF
      jis_code = ((ku + 0x20) << 8) | (ten + 0x20)
      direct[codepoint] = jis_code
      count += 1
    rescue Encoding::UndefinedConversionError, Encoding::InvalidByteSequenceError
      next
    end
  end
end

$stderr.puts "Generated #{count} Unicode-to-JIS mappings (128 KB direct table)"

# Header file
header_path = output.sub(/\.c$/, ".h")

header = <<~HEADER
  // Generated by gen_uni2jis.rb
  // Unicode (BMP) to JIS X 0208 direct lookup table.
  // O(1) lookup: uni2jis_direct[codepoint] returns JIS code (0 = unmapped).
  //
  // JIS code format: high byte = ku+0x20, low byte = ten+0x20
  // Convert to linear index with: (ku-1)*94 + (ten-1)

  #ifndef UNI2JIS_TABLE_H
  #define UNI2JIS_TABLE_H

  #include <stdint.h>

  extern const uint16_t uni2jis_direct[65536];

  // Direct table lookup. Returns JIS code or 0 if not found.
  static inline uint16_t uni2jis_lookup(uint32_t cp) {
      if (cp > 0xFFFF) return 0;
      return uni2jis_direct[cp];
  }

  #endif
HEADER

File.write(header_path, header)
$stderr.puts "Wrote #{header_path}"

# C source file
src_lines = []
src_lines << "// Generated by gen_uni2jis.rb"
src_lines << "#include \"uni2jis_table.h\""
src_lines << ""
src_lines << "const uint16_t uni2jis_direct[65536] = {"

direct.each_slice(16) do |chunk|
  src_lines << "    " + chunk.map { |v| "0x%04X" % v }.join(",") + ","
end

src_lines << "};"
src_lines << ""

File.write(output, src_lines.join("\n"))
$stderr.puts "Wrote #{output} (#{count} mappings, 128 KB)"
