#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate a Unicode-to-JIS X 0208 conversion table as a C header.
# Uses Ruby's built-in EUC-JP encoding to obtain the mapping.
#
# Usage: ruby gen_uni2jis.rb [-o FILE]

require "optparse"

output = nil
OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} [-o FILE]"
  opts.on("-o FILE", "Output file (default: stdout)") { |f| output = f }
end.parse!

# Build Unicode codepoint -> JIS code mapping via EUC-JP encoding.
# In EUC-JP, a JIS X 0208 character with ku/ten values is encoded as
# (ku + 0xA0, ten + 0xA0). We iterate all 94x94 positions and convert
# each to UTF-8 to discover its Unicode codepoint.
mapping = [] # array of [unicode_codepoint, jis_code]

(1..94).each do |ku|
  (1..94).each do |ten|
    euc_bytes = [ku + 0xA0, ten + 0xA0].pack("CC").force_encoding("EUC-JP")
    begin
      utf8 = euc_bytes.encode("UTF-8")
      codepoint = utf8.ord
      jis_code = ((ku + 0x20) << 8) | (ten + 0x20)
      mapping << [codepoint, jis_code]
    rescue Encoding::UndefinedConversionError, Encoding::InvalidByteSequenceError
      next
    end
  end
end

# Sort by Unicode codepoint for binary search
mapping.sort_by! { |cp, _| cp }

$stderr.puts "Generated #{mapping.size} Unicode-to-JIS mappings"

lines = []
lines << "// Generated by gen_uni2jis.rb"
lines << "// Unicode (BMP) to JIS X 0208 conversion table, sorted by Unicode codepoint."
lines << "// Use binary search to look up a Unicode codepoint and get the JIS code."
lines << "//"
lines << "// JIS code format: high byte = ku+0x20, low byte = ten+0x20"
lines << "// Convert to linear index with: (ku-1)*94 + (ten-1)"
lines << ""
lines << "#ifndef UNI2JIS_TABLE_H"
lines << "#define UNI2JIS_TABLE_H"
lines << ""
lines << "#include <stdint.h>"
lines << ""
lines << "typedef struct {"
lines << "    uint16_t unicode;  // Unicode codepoint (BMP)"
lines << "    uint16_t jis;      // JIS X 0208 code"
lines << "} uni2jis_entry_t;"
lines << ""
lines << "static const uni2jis_entry_t uni2jis_table[] = {"

mapping.each do |cp, jis|
  char_comment = ""
  if cp >= 0x20 && cp < 0x7F
    char_comment = " '%s'" % cp.chr
  elsif cp >= 0x80
    char_comment = " %s" % [cp].pack("U")
  end
  lines << "    {0x%04X, 0x%04X}, //%s" % [cp, jis, char_comment]
end

lines << "};"
lines << ""
lines << "#define UNI2JIS_TABLE_SIZE #{mapping.size}"
lines << ""
lines << "#endif"
lines << ""

result = lines.join("\n")

if output
  File.write(output, result)
  $stderr.puts "Wrote #{output} (#{mapping.size} entries, #{result.bytesize} bytes)"
else
  puts result
end
