#!/usr/bin/env ruby
# frozen_string_literal: true

# TTF to C header converter for dvi_font_t.
# Uses FreeType to render glyphs at exact pixel size.
#
# Usage: ruby ttf2c.rb <input.ttf> [options]
#   -o FILE     Output file (default: stdout)
#   -n NAME     Font variable name (default: derived from filename)
#   -s SIZE     Pixel size (default: 12)
#   -r RANGE    Character range as "first-last" (default: 0x20-0x7f)
#   --jis       JIS X 0208 mode: generate JIS-indexed font via Unicode mapping

require "optparse"
require "freetype"

options = {
  name: nil,
  output: nil,
  size: 12,
  range: "0x20-0x7f",
  jis: false
}

OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} <input.ttf> [options]"
  opts.on("-o FILE", "Output file") { |f| options[:output] = f }
  opts.on("-n NAME", "Font variable name") { |n| options[:name] = n }
  opts.on("-s SIZE", Integer, "Pixel size") { |s| options[:size] = s }
  opts.on("-r RANGE", "Character range (e.g., 0x20-0x7f)") { |r| options[:range] = r }
  opts.on("--jis", "JIS X 0208 mode") { options[:jis] = true }
end.parse!

input_path = ARGV[0] or abort "Error: no input TTF file specified"
font_name = options[:name] || File.basename(input_path, ".*").gsub(/[^a-zA-Z0-9_]/, "_")

font = FreeType::API::Font.open(input_path)
font.set_char_size(0, options[:size] * 64, 72, 72)

# Render a glyph and return {bitmap: [row_bytes...], width:, height:, advance:}
# Bitmap rows are MSB-first, padded to full bytes.
def render_glyph(font, codepoint, target_height, glyph_width)
  g = font.glyph(codepoint)
  bm = g[:bitmap]
  w = bm[:width]
  h = bm[:rows]
  advance = g[:advance][:x] >> 6
  bitmap_top = g[:bitmap_top]
  bitmap_left = g[:bitmap_left]

  # Place into target_height bitmap, aligned from the top.
  # bitmap_top = distance from baseline to top of bitmap.
  # We align all glyphs so that baseline is at (target_height - 1).
  y_start = (target_height - 1) - bitmap_top

  src_bytes_per_row = (w + 7) / 8
  dst_bytes_per_row = (glyph_width + 7) / 8
  buf = bm[:buffer]

  # Shift to position glyph at bitmap_left within glyph_width storage.
  # FreeType bitmap is MSB-aligned within src_bytes_per_row.
  shift = (dst_bytes_per_row - src_bytes_per_row) * 8 - bitmap_left

  rows = Array.new(target_height, 0)
  h.times do |src_y|
    dst_y = y_start + src_y
    next if dst_y < 0 || dst_y >= target_height

    # Read source row
    val = 0
    src_bytes_per_row.times do |b|
      val = (val << 8) | buf.get_uint8(src_y * bm[:pitch] + b)
    end

    val = shift > 0 ? (val << shift) : (val >> -shift)

    # Mask to glyph_width
    mask = ((1 << glyph_width) - 1) << (dst_bytes_per_row * 8 - glyph_width)
    rows[dst_y] = val & mask
  end

  {rows: rows, width: w, advance: advance}
end

# Determine max glyph dimensions for the character set
def scan_dimensions(font, codepoints, pixel_size)
  max_width = 0
  max_height = 0
  codepoints.each do |cp|
    g = font.glyph(cp)
    bm = g[:bitmap]
    w = bm[:width] + g[:bitmap_left]
    max_width = w if w > max_width
    h = bm[:rows]
    max_height = h if h > max_height
  end
  # Height is the pixel size (ascent + descent)
  [max_width, pixel_size]
end

def pack_rows(rows, glyph_width)
  bytes_per_row = (glyph_width + 7) / 8
  rows.flat_map do |row|
    # Shift row to fill glyph_width from MSB
    bytes_per_row.times.map do |b|
      (row >> (8 * (bytes_per_row - 1 - b))) & 0xFF
    end
  end
end

# Build Unicode -> JIS linear index mapping
def build_unicode_to_jis_map
  map = {}
  (1..94).each do |ku|
    (1..94).each do |ten|
      euc = [ku + 0xA0, ten + 0xA0].pack("CC").force_encoding("EUC-JP")
      begin
        cp = euc.encode("UTF-8").ord
        map[cp] = (ku - 1) * 94 + (ten - 1)
      rescue Encoding::UndefinedConversionError, Encoding::InvalidByteSequenceError
        next
      end
    end
  end
  map
end

if options[:jis]
  # JIS mode: generate JIS-indexed font from Unicode TTF
  uni2jis = build_unicode_to_jis_map
  num_chars = 94 * 94

  # Scan all JIS-mapped characters to determine dimensions
  jis_codepoints = uni2jis.keys
  glyph_width, glyph_height = scan_dimensions(font, jis_codepoints, options[:size])
  bytes_per_row = (glyph_width + 7) / 8
  bytes_per_glyph = bytes_per_row * glyph_height

  # Build JIS index -> rendered glyph map
  jis2uni = {}
  uni2jis.each { |cp, idx| jis2uni[idx] = cp }

  rendered = {}
  advances = {}
  jis2uni.each do |idx, cp|
    r = render_glyph(font, cp, glyph_height, glyph_width)
    rendered[idx] = r
    advances[idx] = r[:advance]
  end

  populated = rendered.size
  is_proportional = advances.values.uniq.length > 1
  $stderr.puts "JIS mode: #{populated}/#{num_chars} slots, #{glyph_width}x#{glyph_height}, proportional=#{is_proportional}"

  guard = "DVI_FONT_#{font_name.upcase}_H"
  lines = []
  lines << "// Generated by ttf2c.rb (JIS X 0208, from TTF via FreeType)"
  lines << "#ifndef #{guard}"
  lines << "#define #{guard}"
  lines << ""
  lines << "#include \"dvi_font.h\""
  lines << ""
  lines << "static const uint8_t font_#{font_name}_bitmap[] = {"

  num_chars.times do |idx|
    r = rendered[idx]
    bytes = r ? pack_rows(r[:rows], glyph_width) : Array.new(bytes_per_glyph, 0)
    hex = bytes.map { |b| "0x%02x" % b }.join(", ")
    ku = idx / 94 + 1
    ten = idx % 94 + 1
    lines << "    #{hex},  // idx=%d ku=%d ten=%d" % [idx, ku, ten]
  end

  lines << "};"

  if is_proportional
    lines << ""
    lines << "static const uint8_t font_#{font_name}_widths[] = {"
    num_chars.times.each_slice(16) do |indices|
      vals = indices.map { |idx| advances[idx] || glyph_width }
      lines << "    " + vals.map { |v| "%2d" % v }.join(", ") + ","
    end
    lines << "};"
  end

  lines << ""
  lines << "static const dvi_font_t font_#{font_name} = {"
  lines << "    .glyph_width  = #{glyph_width},"
  lines << "    .glyph_height = #{glyph_height},"
  lines << "    .first_char   = 0,"
  lines << "    .num_chars    = #{num_chars},"
  lines << "    .bitmap       = font_#{font_name}_bitmap,"
  lines << "    .widths       = font_#{font_name}_widths," if is_proportional
  lines << "};"
  lines << ""
  lines << "#endif"
  lines << ""

else
  # ASCII/Latin mode
  range_parts = options[:range].split("-")
  first_char = Integer(range_parts[0])
  last_char = Integer(range_parts[1])
  codepoints = (first_char..last_char).to_a

  glyph_width, glyph_height = scan_dimensions(font, codepoints, options[:size])
  bytes_per_row = (glyph_width + 7) / 8
  bytes_per_glyph = bytes_per_row * glyph_height

  # Render all glyphs
  all_advances = []
  guard = "DVI_FONT_#{font_name.upcase}_H"
  lines = []
  lines << "// Generated by ttf2c.rb (from TTF via FreeType)"
  lines << "#ifndef #{guard}"
  lines << "#define #{guard}"
  lines << ""
  lines << "#include \"dvi_font.h\""
  lines << ""
  lines << "static const uint8_t font_#{font_name}_bitmap[] = {"

  codepoints.each do |cp|
    r = render_glyph(font, cp, glyph_height, glyph_width)
    bytes = pack_rows(r[:rows], glyph_width)
    all_advances << r[:advance]
    hex = bytes.map { |b| "0x%02x" % b }.join(", ")
    if cp >= 0x20 && cp <= 0x7E
      lines << "    #{hex},  // 0x%02x '%s'" % [cp, cp.chr]
    else
      lines << "    #{hex},  // 0x%02x" % cp
    end
  end

  lines << "};"

  is_proportional = all_advances.uniq.length > 1
  if is_proportional
    lines << ""
    lines << "static const uint8_t font_#{font_name}_widths[] = {"
    all_advances.each_slice(16) do |chunk|
      lines << "    " + chunk.map { |v| "%2d" % v }.join(", ") + ","
    end
    lines << "};"
  end

  num_chars = last_char - first_char + 1
  lines << ""
  lines << "static const dvi_font_t font_#{font_name} = {"
  lines << "    .glyph_width  = #{glyph_width},"
  lines << "    .glyph_height = #{glyph_height},"
  lines << "    .first_char   = 0x%04x," % first_char
  lines << "    .num_chars    = #{num_chars},"
  lines << "    .bitmap       = font_#{font_name}_bitmap,"
  lines << "    .widths       = font_#{font_name}_widths," if is_proportional
  lines << "};"
  lines << ""
  lines << "#endif"
  lines << ""

  $stderr.puts "#{font_name}, #{glyph_width}x#{glyph_height}, chars 0x%02x-0x%02x, proportional=#{is_proportional}" % [first_char, last_char]
end

result = lines.join("\n")
if options[:output]
  File.write(options[:output], result)
  $stderr.puts "Wrote #{options[:output]}"
else
  puts result
end
