// The Unicode-to-JIS lookup table (uni2jis_direct[]) is generated by
// lib/scripts/gen_uni2jis.rb into the gem build's include directory and is
// shared by the text core (src/dvi_text.c) and the graphics text renderer
// (src/dvi_graphics_text.c), both of which call the inline uni2jis_lookup().
//
// On RP2350 the generated table is compiled into the picoruby-dvi CMake library
// (see CMakeLists.txt). Builds that go entirely through PicoRuby rake, with no
// CMake step (wasm and other POSIX ports), have no other place to compile it, so
// pull it into libmruby here. The guard keeps RP2350 from compiling it twice.
#if defined(PICORB_PLATFORM_POSIX)
#include "uni2jis_table.c"
#endif
