// The Unicode-to-JIS lookup table (uni2jis_direct[]) is generated by
// lib/scripts/gen_uni2jis.rb into the gem build's include directory and is
// shared by the text core (src/dvi_text.c) and the graphics text renderer
// (src/dvi_graphics_text.c), both of which call the inline uni2jis_lookup().
//
// Compiling it here, in a PicoRuby src file, pulls the table into libmruby on
// every platform (RP2350, wasm and other POSIX ports) so the renderers find the
// uni2jis_direct symbol at link time without any CMake-side source entry.
#include "uni2jis_table.c"
