#!/usr/bin/env ruby
# Generate a C header containing Ruby scripts from rootfs/ as byte arrays.
#
# Usage: ruby scripts/gen_ruby_scripts.rb <rootfs_dir> <output_header>

require "pathname"

rootfs_dir = Pathname.new(ARGV[0] || "rootfs")
output_path = ARGV[1] || "ruby_scripts.h"

entries = []
rootfs_dir.glob("**/*.rb").sort.each do |path|
  rel = path.relative_path_from(rootfs_dir).to_s
  var_name = "ruby_script_" + rel.gsub(/[\/.]/, "_")
  fatfs_path = "flash:" + rel
  data = path.binread
  entries << { var_name: var_name, fatfs_path: fatfs_path, data: data }
end

File.open(output_path, "w") do |f|
  f.puts "// Auto-generated by scripts/gen_ruby_scripts.rb -- do not edit"
  f.puts "#pragma once"
  f.puts "#include <stdint.h>"
  f.puts

  entries.each do |e|
    bytes = e[:data].bytes.map { |b| "0x%02x" % b }
    f.puts "static const uint8_t #{e[:var_name]}[] = {"
    bytes.each_slice(16) do |slice|
      f.puts "    #{slice.join(", ")},"
    end
    f.puts "};"
    f.puts
  end

  f.puts "typedef struct {"
  f.puts "    const char *path;"
  f.puts "    const uint8_t *data;"
  f.puts "    uint32_t size;"
  f.puts "} ruby_script_entry_t;"
  f.puts

  f.puts "static const ruby_script_entry_t ruby_scripts[] = {"
  entries.each do |e|
    f.puts "    { \"#{e[:fatfs_path]}\", #{e[:var_name]}, sizeof(#{e[:var_name]}) },"
  end
  f.puts "};"
  f.puts
  f.puts "static const int ruby_scripts_count = sizeof(ruby_scripts) / sizeof(ruby_scripts[0]);"
end

puts "Generated #{output_path} with #{entries.size} script(s)"
