/*
 * WebAssembly boot entry for Harucom OS.
 *
 * Browser counterpart of run_mruby() in src/main.c. This build is based on the
 * upstream picoruby-wasm gem (PICORB_PLATFORM_POSIX), so the hardware HAL,
 * Machine_*, the task scheduler HAL and the io-console / env / rng ports are all
 * provided by picoruby's posix ports, and File/Dir come from mruby-io over the
 * emscripten in-memory filesystem (MEMFS).
 *
 * harucom_init() deploys the rootfs into MEMFS, opens mruby and creates the boot
 * task. The scheduler is driven from JavaScript via mrb_run_step()/mrb_tick_wasm()
 * (provided by the picoruby-wasm gem), so blocking Ruby yields to the browser.
 *
 * Phase 1 boots a minimal bootstrap that reads back the rootfs to validate the
 * VM + filesystem + task scheduler + stdout path. A later phase replaces the
 * bootstrap body with `load "/system.rb"` once the DVI console and keyboard are
 * wired up.
 */

#include <string.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>

#include <emscripten.h>

#include "mruby.h"
#include "mruby/string.h"
#include "mruby_compiler.h"
#include "mrc_utils.h"

/* Generated by scripts/gen_ruby_scripts.rb: ruby_scripts[], ruby_scripts_count. */
#include "ruby_scripts.h"

/* Defined in the picoruby-wasm gem (src/mruby/wasm.c); shared with its
 * mrb_run_step() / mrb_tick_wasm() entry points that the JS loop drives. */
extern mrb_state *global_mrb;

/* This gem only provides the boot entry; there is no Ruby API to register. */
void
mrb_harucom_os_wasm_gem_init(mrb_state *mrb)
{
  (void)mrb;
}

void
mrb_harucom_os_wasm_gem_final(mrb_state *mrb)
{
  (void)mrb;
}

/* Create parent directories for an absolute path like "/lib/foo.rb" in MEMFS. */
static void
ensure_dirs(const char *path)
{
  char buf[256];
  const char *p = path;
  if (*p == '/') p++;
  while (*p) {
    const char *slash = strchr(p, '/');
    if (!slash) break;
    size_t len = (size_t)(slash - path);
    if (len >= sizeof(buf)) return;
    memcpy(buf, path, len);
    buf[len] = '\0';
    mkdir(buf, 0777); /* ignore EEXIST */
    p = slash + 1;
  }
}

/* Deploy the embedded rootfs into the emscripten in-memory filesystem. */
static void
deploy_rootfs(void)
{
  for (int i = 0; i < ruby_scripts_count; i++) {
    const ruby_script_entry_t *e = &ruby_scripts[i];
    ensure_dirs(e->path);
    FILE *f = fopen(e->path, "wb");
    if (!f) {
      fprintf(stderr, "rootfs: fopen(%s) failed\n", e->path);
      continue;
    }
    fwrite(e->data, 1, e->size, f);
    fclose(f);
  }
  fprintf(stderr, "rootfs: deployed %d files to MEMFS\n", ruby_scripts_count);
}

/* Phase 1 bootstrap: read the rootfs back to validate the filesystem. */
static const char ruby_bootstrap[] =
    "begin\n"
    "  puts \"Harucom OS (wasm) booting\"\n"
    "  $LOAD_PATH = [\"/lib\"]\n"
    "  data = File.read(\"/system.rb\")\n"
    "  puts \"system.rb: #{data.bytesize} bytes\"\n"
    "rescue => e\n"
    "  puts \"boot error: #{e.class}: #{e.message}\"\n"
    "end\n";

EMSCRIPTEN_KEEPALIVE
int
harucom_init(void)
{
  deploy_rootfs();

  global_mrb = mrb_open();
  if (!global_mrb) {
    fprintf(stderr, "harucom_init: mrb_open failed\n");
    return -1;
  }
  mrb_state *mrb = global_mrb;

  /* If a gem init raised during mrb_open, report and clear it so boot can
   * continue (otherwise every gem after the failing one is skipped). */
  if (mrb->exc) {
    struct RClass *ec = mrb_obj_class(mrb, mrb_obj_value(mrb->exc));
    mrb_value m = mrb_funcall(mrb, mrb_obj_value(mrb->exc), "message", 0);
    fprintf(stderr, "harucom_init: gem init raised %s: %s\n",
            ec ? mrb_class_name(mrb, ec) : "?",
            mrb_string_p(m) ? RSTRING_PTR(m) : "(no message)");
    mrb->exc = NULL;
  }

  mrb_define_global_const(mrb, "HARUCOM_VERSION", mrb_str_new_cstr(mrb, "wasm"));
  mrb_define_global_const(mrb, "HARUCOM_BUILD_DATE", mrb_str_new_cstr(mrb, "wasm"));

  mrc_ccontext *cc = mrc_ccontext_new(mrb);
  if (!cc) {
    fprintf(stderr, "harucom_init: ccontext_new failed\n");
    return -1;
  }
  const uint8_t *src = (const uint8_t *)ruby_bootstrap;
  mrc_irep *irep = mrc_load_string_cxt(cc, &src, strlen(ruby_bootstrap));
  if (!irep) {
    fprintf(stderr, "harucom_init: bootstrap compile failed\n");
    mrc_ccontext_free(cc);
    return -1;
  }

  mrb_value task = mrc_create_task(cc, irep, mrb_str_new_lit(mrb, "main"),
                                   mrb_nil_value(),
                                   mrb_obj_value(mrb->object_class));
  mrc_ccontext_free(cc);
  if (mrb_nil_p(task)) {
    fprintf(stderr, "harucom_init: create_task failed\n");
    return -1;
  }

  return 0;
}
