/*
 * WebAssembly boot entry for Harucom OS. This is the browser counterpart of
 * run_mruby() in src/main.c. It is built on the picoruby-wasm gem
 * (PICORB_PLATFORM_POSIX). The hardware HAL, Machine_*, the scheduler HAL and the
 * io-console / env / rng ports all come from picoruby's posix ports. File and Dir
 * use the emscripten in-memory filesystem (MEMFS).
 */

#include <string.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>

#include <emscripten.h>

#include "mruby.h"
#include "mruby/string.h"
#include "mruby/variable.h"
#include "mruby/presym.h"

/* Generated by scripts/gen_ruby_scripts.rb: ruby_scripts[], ruby_scripts_count. */
#include "ruby_scripts.h"

/* Defined in the picoruby-wasm gem (src/mruby/wasm.c). The JS loop drives
 * mrb_run_step() / mrb_tick_wasm(). Both use global_mrb. picorb_create_task()
 * compiles a code string and enqueues it as a task. */
extern mrb_state *global_mrb;
extern int picorb_create_task(const char *code);

/* DVI text-mode browser port: wire the shared text core to the framebuffer and
 * load the fonts (mrbgems/picoruby-dvi/ports/posix/dvi_wasm.c). */
extern void dvi_wasm_init(void);

/* IME dictionary browser port: load the emcc-embedded /dict.bin
 * (mrbgems/harucom-os-dict/ports/posix/dict_region.c). */
extern void dict_wasm_init(void);

/* ADC pad shim. It replaces picoruby-adc. The browser has no ADC. The ADC class
 * below returns a raw value that JavaScript injects from the on-screen D-pads.
 * Board::Pad decodes that value. pad_raw is indexed by pad: 0 is pin 28 and 1 is
 * pin 29. An idle pad reads 4095. */
#define HARUCOM_PAD_COUNT 2
static uint16_t pad_raw[HARUCOM_PAD_COUNT] = { 4095, 4095 };

static int
pad_index_for_pin(int pin)
{
  if (pin == 28) return 0;
  if (pin == 29) return 1;
  return -1;
}

EMSCRIPTEN_KEEPALIVE
void
harucom_pad_set(int index, int raw)
{
  if (index >= 0 && index < HARUCOM_PAD_COUNT) {
    pad_raw[index] = (uint16_t)raw;
  }
}

static mrb_value
mrb_adc_initialize(mrb_state *mrb, mrb_value self)
{
  mrb_int pin;
  mrb_get_args(mrb, "i", &pin);
  mrb_iv_set(mrb, self, MRB_IVSYM(input), mrb_fixnum_value(pin));
  return self;
}

static mrb_value
mrb_adc_read_raw(mrb_state *mrb, mrb_value self)
{
  mrb_value pinv = mrb_iv_get(mrb, self, MRB_IVSYM(input));
  int idx = pad_index_for_pin((int)mrb_fixnum(pinv));
  return mrb_fixnum_value(idx >= 0 ? pad_raw[idx] : 4095);
}

/* Register the wasm ADC pad shim (Board::Pad's only hardware dependency). */
void
mrb_harucom_os_wasm_gem_init(mrb_state *mrb)
{
  struct RClass *class_ADC = mrb_define_class_id(mrb, MRB_SYM(ADC), mrb->object_class);
  mrb_define_method_id(mrb, class_ADC, MRB_SYM(initialize), mrb_adc_initialize, MRB_ARGS_REQ(1));
  mrb_define_method_id(mrb, class_ADC, MRB_SYM(read_raw), mrb_adc_read_raw, MRB_ARGS_NONE());
}

void
mrb_harucom_os_wasm_gem_final(mrb_state *mrb)
{
  (void)mrb;
}

/* Create parent directories for an absolute path like "/lib/foo.rb" in MEMFS. */
static void
ensure_dirs(const char *path)
{
  char buf[256];
  const char *p = path;
  if (*p == '/') p++;
  while (*p) {
    const char *slash = strchr(p, '/');
    if (!slash) break;
    size_t len = (size_t)(slash - path);
    if (len >= sizeof(buf)) return;
    memcpy(buf, path, len);
    buf[len] = '\0';
    mkdir(buf, 0777); /* ignore EEXIST */
    p = slash + 1;
  }
}

/* Deploy the embedded rootfs into MEMFS. MEMFS starts empty on every page load.
 * So every boot redeploys it. The board's init_rootfs.c hash-gates against flash
 * instead. Here that is not needed. */
static void
deploy_rootfs(void)
{
  for (int i = 0; i < ruby_scripts_count; i++) {
    const ruby_script_entry_t *e = &ruby_scripts[i];
    ensure_dirs(e->path);
    FILE *f = fopen(e->path, "wb");
    if (!f) {
      fprintf(stderr, "rootfs: fopen(%s) failed\n", e->path);
      continue;
    }
    fwrite(e->data, 1, e->size, f);
    fclose(f);
  }
  fprintf(stderr, "rootfs: deployed %d files to MEMFS\n", ruby_scripts_count);
}

/* Boot like the board (src/main.c), but without the littlefs/VFS mount. Set the
 * require path to /lib and run /system.rb. That starts the Console, keyboard and
 * IRB. */
static const char ruby_bootstrap[] =
    "$LOAD_PATH = [\"/lib\"]\n"
    "load \"/system.rb\"\n";

/* Preemptive scheduling for the browser. The board expires a task's timeslice
 * from a 1ms timer interrupt. The VM checks that flag once per opcode. The browser
 * thread cannot be interrupted. So a Ruby loop that never yields would freeze the
 * tab. The VM calls code_fetch_hook on every opcode. Count opcodes here and ask
 * for a task switch after a budget. This makes the wasm scheduler preemptive like
 * the board. */
#define PREEMPT_OP_BUDGET 30000
static void
preempt_hook(mrb_state *mrb, const struct mrb_irep *irep, const mrb_code *pc, mrb_value *regs)
{
  (void)irep;
  (void)pc;
  (void)regs;
  static uint32_t ops = 0;
  if (++ops >= PREEMPT_OP_BUDGET) {
    ops = 0;
    mrb->task.switching = TRUE; /* yield at the next opcode, like the timer tick */
  }
}

EMSCRIPTEN_KEEPALIVE
int
harucom_init(void)
{
  deploy_rootfs();

  global_mrb = mrb_open();
  if (!global_mrb) {
    fprintf(stderr, "harucom_init: mrb_open failed\n");
    return -1;
  }
  mrb_state *mrb = global_mrb;

  /* Report and clear a gem-init exception left pending by mrb_open. This is
   * diagnostic only. The failed gem and the ones after it were already skipped
   * inside mrb_open. Clearing it just keeps the stale exception from breaking the
   * bootstrap. */
  if (mrb->exc) {
    struct RClass *ec = mrb_obj_class(mrb, mrb_obj_value(mrb->exc));
    mrb_value m = mrb_funcall(mrb, mrb_obj_value(mrb->exc), "message", 0);
    fprintf(stderr, "harucom_init: gem init raised %s: %s\n",
            ec ? mrb_class_name(mrb, ec) : "?",
            mrb_string_p(m) ? RSTRING_PTR(m) : "(no message)");
    mrb->exc = NULL;
  }

  mrb->code_fetch_hook = preempt_hook; /* preempt yield-less loops (see preempt_hook) */

  dvi_wasm_init(); /* DVI text surface ready before the Console draws */
  dict_wasm_init();

  mrb_define_global_const(mrb, "HARUCOM_VERSION", mrb_str_new_cstr(mrb, "wasm"));
  mrb_define_global_const(mrb, "HARUCOM_BUILD_DATE", mrb_str_new_cstr(mrb, "wasm"));

  /* Enqueue the boot task via picoruby-wasm. It uses the same global_mrb. The call
   * returns 0 on success and -1 on error. */
  return picorb_create_task(ruby_bootstrap);
}

/* Enqueue a Ruby code string as a task on the same VM. The browser Engine calls
 * this (after writing the funicular UI sources into MEMFS under /_web) to start
 * and hot-reload the UI. Returns 0 on success, -1 on error. */
EMSCRIPTEN_KEEPALIVE
int
harucom_run_ruby(const char *code)
{
  if (!global_mrb) return -1;
  return picorb_create_task(code);
}
