/*
 * WebAssembly boot entry for Harucom OS.
 *
 * Browser counterpart of run_mruby() in src/main.c. This build is based on the
 * upstream picoruby-wasm gem (PICORB_PLATFORM_POSIX), so the hardware HAL,
 * Machine_*, the task scheduler HAL and the io-console / env / rng ports are all
 * provided by picoruby's posix ports, and File/Dir come from mruby-io over the
 * emscripten in-memory filesystem (MEMFS).
 *
 * harucom_init() deploys the rootfs into MEMFS, opens mruby and creates the boot
 * task. The scheduler is driven from JavaScript via mrb_run_step()/mrb_tick_wasm()
 * (provided by the picoruby-wasm gem), so blocking Ruby yields to the browser.
 *
 * The boot task mirrors the board bootstrap (src/main.c) minus the littlefs/VFS
 * mount: it sets $LOAD_PATH to /lib and `load`s /system.rb, which brings up the
 * Console, keyboard and IRB on the DVI text surface.
 */

#include <string.h>
#include <stdio.h>
#include <sys/stat.h>
#include <sys/types.h>

#include <emscripten.h>

#include "mruby.h"
#include "mruby/string.h"
#include "mruby/variable.h"
#include "mruby/presym.h"

/* Generated by scripts/gen_ruby_scripts.rb: ruby_scripts[], ruby_scripts_count. */
#include "ruby_scripts.h"

/* Defined in the picoruby-wasm gem (src/mruby/wasm.c). global_mrb is shared with
 * its mrb_run_step() / mrb_tick_wasm() entry points that the JS loop drives;
 * picorb_create_task() compiles a string and enqueues it as a task. */
extern mrb_state *global_mrb;
extern int picorb_create_task(const char *code);

/* DVI text-mode browser port (mrbgems/picoruby-dvi/ports/posix/dvi_wasm.c).
 * dvi_wasm_init() wires the shared text core to the framebuffer and loads the
 * M+ fonts; the Ruby Console then fills the text VRAM and commits it into the
 * RGB332 framebuffer that the JS canvas blit reads. */
extern void dvi_wasm_init(void);

/* IME dictionary browser port (mrbgems/harucom-os-dict/ports/posix/dict_region.c).
 * Loads the emcc-embedded /dict.bin so InputMethod.skk_lookup / tcode_lookup work. */
extern void dict_wasm_init(void);

/* ---------------------------------------------------------------------------
 * ADC pad simulation.
 *
 * The board's Board::Pad reads a resistor-ladder over ADC: a 1k pull-up to 3V3
 * and four buttons (1k/2.2k/4.7k/10k to GND) per pad, so the 12-bit ADC value
 * encodes which buttons are held (Board::Pad decodes it). There is no ADC in the
 * browser, so define a minimal ADC class whose read_raw returns a value JavaScript
 * injects from on-screen D-pads (it computes the resistor-ladder value for the
 * pressed buttons). This replaces the picoruby-adc gem for the wasm build.
 *
 * pad_raw is indexed by pad (0 = PAD0_PIN 28, 1 = PAD1_PIN 29); idle = 4095.
 */
#define HARUCOM_PAD_COUNT 2
static uint16_t pad_raw[HARUCOM_PAD_COUNT] = { 4095, 4095 };

static int
pad_index_for_pin(int pin)
{
  if (pin == 28) return 0;
  if (pin == 29) return 1;
  return -1;
}

EMSCRIPTEN_KEEPALIVE
void
harucom_pad_set(int index, int raw)
{
  if (index >= 0 && index < HARUCOM_PAD_COUNT) {
    pad_raw[index] = (uint16_t)raw;
  }
}

static mrb_value
mrb_adc_initialize(mrb_state *mrb, mrb_value self)
{
  mrb_int pin;
  mrb_get_args(mrb, "i", &pin);
  mrb_iv_set(mrb, self, MRB_IVSYM(input), mrb_fixnum_value(pin));
  return self;
}

static mrb_value
mrb_adc_read_raw(mrb_state *mrb, mrb_value self)
{
  mrb_value pinv = mrb_iv_get(mrb, self, MRB_IVSYM(input));
  int idx = pad_index_for_pin((int)mrb_fixnum(pinv));
  return mrb_fixnum_value(idx >= 0 ? pad_raw[idx] : 4095);
}

/* Register the wasm ADC pad shim (Board::Pad's only hardware dependency). */
void
mrb_harucom_os_wasm_gem_init(mrb_state *mrb)
{
  struct RClass *class_ADC = mrb_define_class_id(mrb, MRB_SYM(ADC), mrb->object_class);
  mrb_define_method_id(mrb, class_ADC, MRB_SYM(initialize), mrb_adc_initialize, MRB_ARGS_REQ(1));
  mrb_define_method_id(mrb, class_ADC, MRB_SYM(read_raw), mrb_adc_read_raw, MRB_ARGS_NONE());
}

void
mrb_harucom_os_wasm_gem_final(mrb_state *mrb)
{
  (void)mrb;
}

/* Create parent directories for an absolute path like "/lib/foo.rb" in MEMFS. */
static void
ensure_dirs(const char *path)
{
  char buf[256];
  const char *p = path;
  if (*p == '/') p++;
  while (*p) {
    const char *slash = strchr(p, '/');
    if (!slash) break;
    size_t len = (size_t)(slash - path);
    if (len >= sizeof(buf)) return;
    memcpy(buf, path, len);
    buf[len] = '\0';
    mkdir(buf, 0777); /* ignore EEXIST */
    p = slash + 1;
  }
}

/* Deploy the embedded rootfs into the emscripten in-memory filesystem. Unlike
 * the board's init_rootfs.c, which hash-gates deployment against persistent
 * flash, MEMFS starts empty on every page load, so every boot simply redeploys. */
static void
deploy_rootfs(void)
{
  for (int i = 0; i < ruby_scripts_count; i++) {
    const ruby_script_entry_t *e = &ruby_scripts[i];
    ensure_dirs(e->path);
    FILE *f = fopen(e->path, "wb");
    if (!f) {
      fprintf(stderr, "rootfs: fopen(%s) failed\n", e->path);
      continue;
    }
    fwrite(e->data, 1, e->size, f);
    fclose(f);
  }
  fprintf(stderr, "rootfs: deployed %d files to MEMFS\n", ruby_scripts_count);
}

/* Boot bootstrap: mirror the board (src/main.c) without the littlefs/VFS mount,
 * since the rootfs lives in MEMFS. $LOAD_PATH lets require resolve /lib/*.rb, and
 * `load` runs /system.rb (which starts the Console, keyboard task and IRB). */
static const char ruby_bootstrap[] =
    "$LOAD_PATH = [\"/lib\"]\n"
    "load \"/system.rb\"\n";

EMSCRIPTEN_KEEPALIVE
int
harucom_init(void)
{
  deploy_rootfs();

  global_mrb = mrb_open();
  if (!global_mrb) {
    fprintf(stderr, "harucom_init: mrb_open failed\n");
    return -1;
  }
  mrb_state *mrb = global_mrb;

  /* Report (and clear) a gem-init exception left pending by mrb_open. This is
   * diagnostic only: mrb_init_mrbgems ran inside mrb_open and already skipped
   * every gem after the one that raised, so clearing mrb->exc cannot recover
   * those gems; it only keeps the stale exception from poisoning the bootstrap. */
  if (mrb->exc) {
    struct RClass *ec = mrb_obj_class(mrb, mrb_obj_value(mrb->exc));
    mrb_value m = mrb_funcall(mrb, mrb_obj_value(mrb->exc), "message", 0);
    fprintf(stderr, "harucom_init: gem init raised %s: %s\n",
            ec ? mrb_class_name(mrb, ec) : "?",
            mrb_string_p(m) ? RSTRING_PTR(m) : "(no message)");
    mrb->exc = NULL;
  }

  /* Initialize the DVI text surface (VRAM, fonts, framebuffer) before the boot
   * task runs, so the Ruby Console has a cleared screen to draw into. */
  dvi_wasm_init();

  /* Load the embedded IME dictionary so SKK / T-Code conversion works. */
  dict_wasm_init();

  mrb_define_global_const(mrb, "HARUCOM_VERSION", mrb_str_new_cstr(mrb, "wasm"));
  mrb_define_global_const(mrb, "HARUCOM_BUILD_DATE", mrb_str_new_cstr(mrb, "wasm"));

  /* Compile and enqueue the boot task. Reuse picoruby-wasm's task creation
   * (it operates on the same global_mrb) instead of duplicating the compiler
   * dance; it returns 0 on success and -1 (with a diagnostic) on failure. */
  return picorb_create_task(ruby_bootstrap);
}
